### ISSUE TITLE
Game doesnt work

### ISSUE THREAD

**Issue by abprince** [maddox05/Comment-Game-Controller#1]
it does not work or may be some of the files are missing

**Comment by maddox05** [comment]
im not sure what issue you are having, could you be more clear or maybe show an error message? I'll read back over the code.

**Comment by abprince** [comment]
there is no error message , but when I run the game it does not respond to the comments

**Comment by maddox05** [comment]
the game presses keys for you so make sure the game you want to play you have focused. If that does not work, then app must be broken. i'll look into it but that should be the problem. I also updated releases with a new ver so please try that.

**Comment by maddox05** [comment]
please give an exact bug or an error and not "it does not work" please.

**Comment by solexo** [comment]
hello the script work and show the comment interaction PS 
Entered username: @m7am3
Detected comment: up
Detected language: english
Pressed key: z
but the game window doesn't appear

**Comment by maddox05** [comment]
what?

**Comment by solexo** [comment]
when i start the code it work fine but the game window don't open
